version: '3.8'

services:
  clipar:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - /var/lib/docker/volumes/downloads/_data:/app/clips
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    stdin_open: true
    tty: true
